---
# tasks file for molecule-delegated

- debug: 
    var: ansible_distribution

- debug:
    var: ansible_distribution_version

- shell: cat /etc/motd
  changed_when: false
  register: r

- debug:
    var: r.stdout_lines
